#!/usr/bin/env bash
# displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
n=0
while [ $n -lt 10 ]
do
      if [ $n	-eq 8 ]
      then 
	echo "Best School"
	echo "Hi"
    else
	echo "Best school"
      fi
	((n++))
done 
