#!/usr/bin/env bash
#Checks for a file and handles cases accordingly
filename="school"
if [ -n "$filename" ]
then
    echo "school file exists"
    if [ -p "$filename" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -l "$filename" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
